In [10]:
# import required libraries
import pandas as pd

In [11]:
# import data into a dataframe
df = pd.read_excel('salary_lab3.xlsx')
df

    Unnamed: 0  YearsExperience  Salary
0            0              1.2   39344
1            1              1.4   46206
2            2              1.6   37732
3            3              2.1   43526
4            4              2.3   39892
5            5              3.0   56643
6            6              3.1   60151
7            7              3.3   54446
8            8              3.3   64446
9            9              3.8   57190
10          10              4.0   63219
11          11              4.1   55795
12          12              4.1   56958
13          13              4.2   57082
14          14              4.6   61112
15          15              5.0   67939
16          16              5.2   66030
17          17              5.4   83089
18          18              6.0   81364
19          19              6.1   93941
20          20              6.9   91739
21          21              7.2   98274
22          22              8.0  101303
23          23              8.3  113813
24          24              8.8  109432
25          25              9.1  105583
26          26              9.6  116970
27          27              9.7  112636
28          28             10.4  122392
29          29             10.6  121873

In [14]:
# run standard checks
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       30 non-null     int64
 1   YearsExperience  30 non-null     float64
 2   Salary           30 non-null     int64
dtypes: float64(1), int64(2)
memory usage: 852.0 bytes

In [ ]:
df.describe()

       Unnamed: 0  YearsExperience         Salary
count   30.000000        30.000000      30.000000
mean    14.500000         5.413333   76004.000000
std      8.803408         2.837888   27414.429785
min      0.000000         1.200000   37732.000000
25%      7.250000         3.300000   56721.750000
50%     14.500000         4.800000   65238.000000
75%     21.750000         7.800000  100545.750000
max     29.000000        10.600000  122392.000000

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       30 non-null     int64
 1   YearsExperience  30 non-null     float64
 2   Salary           30 non-null     int64
dtypes: float64(1), int64(2)
memory usage: 852.0 bytes

In [17]:
df.shape

(30, 3)

In [ ]:
# drop unnecessary duplicated index column
df_updated = df.drop('Unnamed: 0', axis=1)
df_updated

    YearsExperience  Salary
0               1.2   39344
1               1.4   46206
2               1.6   37732
3               2.1   43526
4               2.3   39892
5               3.0   56643
6               3.1   60151
7               3.3   54446
8               3.3   64446
9               3.8   57190
10              4.0   63219
11              4.1   55795
12              4.1   56958
13              4.2   57082
14              4.6   61112
15              5.0   67939
16              5.2   66030
17              5.4   83089
18              6.0   81364
19              6.1   93941
20              6.9   91739
21              7.2   98274
22              8.0  101303
23              8.3  113813
24              8.8  109432
25              9.1  105583
26              9.6  116970
27              9.7  112636
28             10.4  122392
29             10.6  121873